"""initial_migration

Revision ID: 422d0737a597
Revises: 
Create Date: 2025-10-08 12:03:01.374614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422d0737a597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueo_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueo_ip_id'), 'bloqueo_ip', ['id'], unique=False)
    op.create_index(op.f('ix_bloqueo_ip_ip_address'), 'bloqueo_ip', ['ip_address'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('categorias_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_categorias_permiso_id'), 'categorias_permiso', ['id'], unique=False)
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('motivo_fallo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_email'), 'intentos_login', ['email'], unique=False)
    op.create_index(op.f('ix_intentos_login_id'), 'intentos_login', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('extensiones_permitidas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_permiso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_dni'), 'usuarios', ['dni'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('numero_expediente', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('path_archivo', sa.String(), nullable=False),
    sa.Column('hash_archivo', sa.String(), nullable=True),
    sa.Column('tamano_archivo', sa.Integer(), nullable=True),
    sa.Column('extension_archivo', sa.String(), nullable=True),
    sa.Column('fecha_ultima_verificacion', sa.DateTime(), nullable=True),
    sa.Column('estado_integridad', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_numero_expediente'), 'documentos', ['numero_expediente'], unique=False)
    op.create_index(op.f('ix_documentos_titulo'), 'documentos', ['titulo'], unique=False)
    op.create_table('historial_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('modificado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_permiso_id'), 'historial_permiso', ['id'], unique=False)
    op.create_table('historial_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_anterior_id', sa.Integer(), nullable=False),
    sa.Column('rol_nuevo_id', sa.Integer(), nullable=False),
    sa.Column('modificado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_anterior_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['rol_nuevo_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_rol_id'), 'historial_rol', ['id'], unique=False)
    op.create_table('registro_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('codigo_respuesta', sa.Integer(), nullable=False),
    sa.Column('mensaje_error', sa.String(), nullable=True),
    sa.Column('tiempo_respuesta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_acceso_id'), 'registro_acceso', ['id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('errores_almacenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_error', sa.String(), nullable=False),
    sa.Column('mensaje_error', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=True),
    sa.Column('acciones_tomadas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errores_almacenamiento_id'), 'errores_almacenamiento', ['id'], unique=False)
    op.create_table('historial_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_acceso_id'), 'historial_acceso', ['id'], unique=False)
    op.create_table('versiones_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('fecha_version', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('path_archivo', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('version_anterior_id', sa.Integer(), nullable=True),
    sa.Column('hash_archivo', sa.String(), nullable=True),
    sa.Column('tamano_archivo', sa.Integer(), nullable=True),
    sa.Column('extension_archivo', sa.String(), nullable=True),
    sa.Column('cambios', sa.Text(), nullable=True),
    sa.Column('es_actual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['version_anterior_id'], ['versiones_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versiones_documento_id'), 'versiones_documento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versiones_documento_id'), table_name='versiones_documento')
    op.drop_table('versiones_documento')
    op.drop_index(op.f('ix_historial_acceso_id'), table_name='historial_acceso')
    op.drop_table('historial_acceso')
    op.drop_index(op.f('ix_errores_almacenamiento_id'), table_name='errores_almacenamiento')
    op.drop_table('errores_almacenamiento')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_registro_acceso_id'), table_name='registro_acceso')
    op.drop_table('registro_acceso')
    op.drop_index(op.f('ix_historial_rol_id'), table_name='historial_rol')
    op.drop_table('historial_rol')
    op.drop_index(op.f('ix_historial_permiso_id'), table_name='historial_permiso')
    op.drop_table('historial_permiso')
    op.drop_index(op.f('ix_documentos_titulo'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_numero_expediente'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_intentos_login_id'), table_name='intentos_login')
    op.drop_index(op.f('ix_intentos_login_email'), table_name='intentos_login')
    op.drop_table('intentos_login')
    op.drop_index(op.f('ix_categorias_permiso_id'), table_name='categorias_permiso')
    op.drop_table('categorias_permiso')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_bloqueo_ip_ip_address'), table_name='bloqueo_ip')
    op.drop_index(op.f('ix_bloqueo_ip_id'), table_name='bloqueo_ip')
    op.drop_table('bloqueo_ip')
    # ### end Alembic commands ###
